name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@0.1.7.1
        with:
          cabal-file: nonempty-wrapper/nonempty-wrapper.cabal
          ubuntu-version: "latest"
          version: 0.1.7.0
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: haskell/ghcup-setup@v1
      with:
        ghc: ${{ matrix.ghc }}
        config: |
          # don't cache metadata files based on last access time
          meta-cache: 0
          # see https://github.com/haskell/ghcup-hs/blob/master/data/config.yaml
          # for full documentation
          url-source:
            - GHCupURL
            - prereleases

    - name: update
      run: |
        cabal update

    - name: Freeze
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal freeze

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('./.plan.json') }}

    - name: Build
      run: |
        cabal build all

    - name: Test
      run: |
        cabal install hspec-discover
        cabal test all

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('./.plan.json') }}
